print("=== List ke Set ===")
data_list = eval(input("Masukkan list (contoh: [1, 2, 3, 2, 4]): "))
print("List awal        :", data_list)
data_set = set(data_list)
print("Set hasil konversi:", data_set)
print()

print("=== Set ke List ===")
data_set2 = eval(input("Masukkan set (contoh: {'apel', 'mangga', 'pisang'}): "))
print("Set awal         :", data_set2)
data_list2 = list(data_set2)
print("List hasil konversi:", data_list2)
print()

print("=== Tuple ke Set ===")
data_tuple = eval(input("Masukkan tuple (contoh: (10, 20, 30, 20)): "))
print("Tuple awal       :", data_tuple)
data_set3 = set(data_tuple)
print("Set hasil konversi:", data_set3)
print()

print("=== Set ke Tuple ===")
data_set4 = eval(input("Masukkan set (contoh: {'Python', 'Java', 'C++'}): "))
print("Set awal         :", data_set4)
data_tuple2 = tuple(data_set4)
print("Tuple hasil konversi:", data_tuple2)